### ISSUE TITLE
Is normalization necessary?

### ISSUE THREAD

**Issue by 943fansi** [yonda-yonda/tadgan#3]
@yonda-yonda Hello, I'm sorry to bother you. I see that your code seems to be missing normalization of the data. In my actual test, when I use `x_train /= np.max(x_train), x_test /= np.min(x_test)` for normalization, the performance of anomaly detection becomes much worse, which seems strange. Do you have any thoughts on this?

**Comment by yonda-yonda** [comment]
@943fansi Sorry for the delay in noticing.
 In [the paper](https://arxiv.org/abs/2009.07769),  the author says
> For each dataset, we first normalize the data betweeen [−1, 1]

I'm just following it.
https://github.com/yonda-yonda/tadgan/blob/master/tadgan/telemanom.py#L13

I don't know wheter the normalization way you are doing it is the same as the way the author is talking about.

**Comment by 943fansi** [comment]
@yonda-yonda Thanks for your answer, I am using min-max normalized to the range [0, 1]. In fact, normalization is useful, I made a mistake in implementing the code, and now it works fine. Thanks again for your patient answer.
